version: '3'
services:
  blue:
    build:
      context: ./blue
    container_name: blue
    ports:
      - "8081:80"
    networks:
      - webnet

  green:
    build:
      context: ./green
    container_name: green
    ports:
      - "8082:80"
    networks:
      - webnet

  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - blue
      - green
    networks:
      - webnet

networks:
  webnet:
